<a href="https://colab.research.google.com/github/ezequielcabeja/Imers-oAlura_DS_A1/blob/main/Imers%C3%A3o_Alura_DS_A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas

# **An√°lise de dados com Pandas**

In [71]:
import pandas as pd
import numpy as np

In [41]:
df=pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [42]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object
 2   employment_type     133349 non-null  object
 3   job_title           133349 non-null  object
 4   salary              133349 non-null  int64
 5   salary_currency     133349 non-null  object
 6   salary_in_usd       133349 non-null  int64
 7   employee_residence  133349 non-null  object
 8   remote_ratio        133349 non-null  int64
 9   company_location    133349 non-null  object
 10  company_size        133349 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB

In [44]:
df.describe()

           work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [45]:
#Dimensao do arquivo (linhas e colunas)
df.shape

(133349, 11)

In [46]:
linhas, colunas = df.shape[0], df.shape[1]
print("Linhas:", linhas)
print("Colunas:", colunas)

Linhas: 133349
Colunas: 11

In [47]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [48]:
#Prompt: Traduza pa mim todas as colunas do dataframe df para Portugu√™s

renomear_colunas = {
    'work_year': 'ano',
    'experience_level': 'senioridade',
    'employment_type': 'contrato',
    'job_title': 'cargo',
    'salary': 'salario',
    'salary_currency': 'moeda',
    'salary_in_usd': 'usd',
    'employee_residence': 'residencia',
    'remote_ratio': 'remoto',
    'company_location': 'empresa',
    'company_size': 'tamanho_empresa'
}

df.rename(columns=renomear_colunas, inplace=True)
df.columns

Index(['ano', 'senioridade', 'contrato', 'cargo', 'salario', 'moeda', 'usd',
       'residencia', 'remoto', 'empresa', 'tamanho_empresa'],
      dtype='object')

In [49]:
df['senioridade'].value_counts()

senioridade
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [50]:
#Promtp: Traduza para portugu√™s as categorias da coluna "senioridade" do dataframe df.
traducao_senioridade = {
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'J√∫nior',
    'EX': 'Executivo'
}

df['senioridade'] = df['senioridade'].replace(traducao_senioridade)
df['senioridade'].value_counts()

senioridade
Senior       77241
Pleno        40465
J√∫nior       12443
Executivo     3200
Name: count, dtype: int64

In [51]:
df['contrato'].value_counts()

contrato
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [52]:
traducao_contrato = {
    'FT': 'Integral',
    'CT': 'Contrato',
    'PT': 'Parcial',
    'FL': 'Freelancer'
}

df['contrato'] = df['contrato'].replace(traducao_contrato)

df['contrato'].value_counts()

contrato
Integral      132563
Contrato         394
Parcial          376
Freelancer        16
Name: count, dtype: int64

In [53]:
df['remoto'].value_counts()

remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [54]:
traducao_remoto = {
    0: 'Presencial',
    50: 'H√≠brido',
    100: 'Remoto'
}

df['remoto'] = df['remoto'].map(traducao_remoto)

df['remoto'].value_counts()

remoto
Presencial    105312
Remoto         27718
H√≠brido          319
Name: count, dtype: int64

In [55]:
df['tamanho_empresa'].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [56]:
traducao_tamanho_empresa = {
    'M': 'M√©dia',
    'L': 'Grande',
    'S': 'Pequena'
}

df['tamanho_empresa'] = df['tamanho_empresa'].replace(traducao_tamanho_empresa)

df['tamanho_empresa'].value_counts()

tamanho_empresa
M√©dia      129561
Grande       3574
Pequena       214
Name: count, dtype: int64

In [57]:
df.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dia
1,2025.0,Senior,Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dia
2,2025.0,Pleno,Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dia
3,2025.0,Pleno,Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dia
4,2025.0,J√∫nior,Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dia

In [58]:
df.describe(include="object")

,senioridade,contrato,cargo,moeda,residencia,remoto,empresa,tamanho_empresa
count,133349,133349,133349,133349,133349,133349,133349,133349
unique,4,4,390,26,102,3,95,3
top,Senior,Integral,Data Scientist,USD,US,Presencial,US,M√©dia
freq,77241,132563,17314,126140,119579,105312,119641,129561

In [59]:
df.describe()

                 ano       salario            usd
count  133339.000000  1.333490e+05  133349.000000
mean     2024.358770  1.632833e+05  157617.272098
std         0.680627  2.173860e+05   74288.363097
min      2020.000000  1.400000e+04   15000.000000
25%      2024.000000  1.060200e+05  106000.000000
50%      2024.000000  1.470000e+05  146206.000000
75%      2025.000000  1.990000e+05  198000.000000
max      2025.000000  3.040000e+07  800000.000000

In [60]:
df.describe(include="all")

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
count,133339.000000,133349,133349,133349,1.333490e+05,133349,133349.000000,133349,133349,133349,133349
unique,NaN,4,4,390,NaN,26,NaN,102,3,95,3
top,NaN,Senior,Integral,Data Scientist,NaN,USD,NaN,US,Presencial,US,M√©dia
freq,NaN,77241,132563,17314,NaN,126140,NaN,119579,105312,119641,129561
mean,2024.358770,NaN,NaN,NaN,1.632833e+05,NaN,157617.272098,NaN,NaN,NaN,NaN
std,0.680627,NaN,NaN,NaN,2.173860e+05,NaN,74288.363097,NaN,NaN,NaN,NaN
min,2020.000000,NaN,NaN,NaN,1.400000e+04,NaN,15000.000000,NaN,NaN,NaN,NaN
25%,2024.000000,NaN,NaN,NaN,1.060200e+05,NaN,106000.000000,NaN,NaN,NaN,NaN
50%,2024.000000,NaN,NaN,NaN,1.470000e+05,NaN,146206.000000,NaN,NaN,NaN,NaN
75%,2025.000000,NaN,NaN,NaN,1.990000e+05,NaN,198000.000000,NaN,NaN,NaN,NaN
max,2025.000000,NaN,NaN,NaN,3.040000e+07,NaN,800000.000000,NaN,NaN,NaN,NaN

# **Prepara√ß√£o e limpeza dos Dados**

PRINT

In [23]:
#Verificar dados Faltantes (se ha valores nulos)
df.isnull()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [28]:
#Buscando total de todos os valores faltantes das respectivas features(em colunas)
df.isnull().sum()

ano                10
senioridade         0
contrato            0
cargo               0
salario             0
moeda               0
usd                 0
residencia          0
remoto              0
empresa             0
tamanho_empresa     0
dtype: int64

In [29]:
#Verificando quais valor fazem parte do atributo "ano", os valores unicos
df["ano"].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [31]:
#Exibindo as linhas que possuem esses elementos faltantes/nulos(NaNs)
df[df.isnull().any(axis=1)]

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
5588,NaN,Senior,FT,Product Manager,184500,USD,184500,US,0,US,M√©dia
59692,NaN,Pleno,FT,Engineer,110000,USD,110000,DE,0,DE,M√©dia
59710,NaN,J√∫nior,FT,Data Scientist,208800,USD,208800,US,0,US,M√©dia
59759,NaN,Senior,FT,Software Engineer,135000,USD,135000,US,0,US,M√©dia
59789,NaN,Senior,FT,Engineer,112000,USD,112000,US,0,US,M√©dia
131000,NaN,Senior,FT,Machine Learning Engineer,163800,USD,163800,US,0,US,M√©dia
131006,NaN,Senior,FT,Data Analytics Manager,204500,USD,204500,US,0,US,M√©dia
133054,NaN,J√∫nior,FT,Data Scientist,40000,USD,40000,JP,100,MY,Grande
133281,NaN,Pleno,FT,Machine Learning Engineer,180000,PLN,46597,PL,100,PL,Grande
133317,NaN,Pleno,FT,Data Scientist,130000,USD,130000,US,50,US,Grande

In [38]:
#Preenchimento de dados em faltas com valores medios. Usando um outro exempo
#Criacao de DataFrame de teste
df_salarios = pd.DataFrame(
    {
    "nome": ["Ana", "Bruno", "Carlos", "Daniel", "Val"],
    "salario": [4000, np.nan, 5000, np.nan, 100000]
    })
df_salarios["salario_media"]=df_salarios["salario"].fillna(df_salarios["salario"].mean().round(2))
#Em caso de outliers, podemos usar a mediana, ja que esta sofre pouco impacto do mesmo.
df_salarios["salario_mediana"]=df_salarios["salario"].fillna(df_salarios["salario"].median())
df_salarios

     nome   salario  salario_media  salario_mediana
0     Ana    4000.0        4000.00           4000.0
1   Bruno       NaN       36333.33           5000.0
2  Carlos    5000.0        5000.00           5000.0
3  Daniel       NaN       36333.33           5000.0
4     Val  100000.0      100000.00         100000.0

In [63]:
#Preenchendo os valores faltantes com os valores anteriores existentes
df_temperaturas = pd.DataFrame({
    "Dia":["segunda", "Ter√ßa", "Quarta", "Quinta", "Sexta"],
    "Temperatura": [30, np.nan, np.nan, 28, 27]
})

df_temperaturas["Preenchido_ffill"] = df_temperaturas["Temperatura"].ffill()
df_temperaturas

       Dia  Temperatura  Preenchido_ffill
0  segunda         30.0              30.0
1    Ter√ßa          NaN              30.0
2   Quarta          NaN              30.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [66]:
#Preenchendo os valores faltantes com os valores posteriores existentes
df_temperaturas = pd.DataFrame({
    "Dia":["segunda", "Ter√ßa", "Quarta", "Quinta", "Sexta"],
    "Temperatura": [30, np.nan, np.nan, 28, 27]
})

df_temperaturas["Preenchido_bfill"] = df_temperaturas["Temperatura"].bfill()
df_temperaturas

       Dia  Temperatura  Preenchido_bfill
0  segunda         30.0              30.0
1    Ter√ßa          NaN              28.0
2   Quarta          NaN              28.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [73]:
df_cidades = pd.DataFrame({
    "nome": ["Ana", "Bruno", "Carlos", "Daniel", "Val"],
    "cidade": ["S√£o Paulo", np.nan, "Curitiba", np.nan, "Bel√©m"]
})

df_cidades["cidade_Preenchida"] = df_cidades["cidade"].fillna("N√£o informado")
df_cidades

     nome     cidade cidade_Preenchida
0     Ana  S√£o Paulo         S√£o Paulo
1   Bruno        NaN     N√£o informado
2  Carlos   Curitiba          Curitiba
3  Daniel        NaN     N√£o informado
4     Val      Bel√©m             Bel√©m

In [74]:
#Agora podemos  voltar o tratamento dos nossos dados originais.
#Por serem dados elevados, vamos excluir os dados faltante, usando sua subdataframe.
df_limpo = df.dropna()

In [75]:
df_limpo.isnull().sum()

ano                0
senioridade        0
contrato           0
cargo              0
salario            0
moeda              0
usd                0
residencia         0
remoto             0
empresa            0
tamanho_empresa    0
dtype: int64

In [76]:
df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025.0,Senior,Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dia
1,2025.0,Senior,Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dia
2,2025.0,Pleno,Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dia
3,2025.0,Pleno,Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dia
4,2025.0,J√∫nior,Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dia

In [77]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ano              133339 non-null  float64
 1   senioridade      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 12.2+ MB

In [80]:
df_limpo = df_limpo.assign(ano = df_limpo["ano"].astype('int64'))
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ano              133339 non-null  int64
 1   senioridade      133339 non-null  object
 2   contrato         133339 non-null  object
 3   cargo            133339 non-null  object
 4   salario          133339 non-null  int64
 5   moeda            133339 non-null  object
 6   usd              133339 non-null  int64
 7   residencia       133339 non-null  object
 8   remoto           133339 non-null  object
 9   empresa          133339 non-null  object
 10  tamanho_empresa  133339 non-null  object
dtypes: int64(3), object(8)
memory usage: 12.2+ MB

In [81]:
df_limpo.head()

,ano,senioridade,contrato,cargo,salario,moeda,usd,residencia,remoto,empresa,tamanho_empresa
0,2025,Senior,Integral,Solutions Engineer,214000,USD,214000,US,Remoto,US,M√©dia
1,2025,Senior,Integral,Solutions Engineer,136000,USD,136000,US,Remoto,US,M√©dia
2,2025,Pleno,Integral,Data Engineer,158800,USD,158800,AU,Presencial,AU,M√©dia
3,2025,Pleno,Integral,Data Engineer,139200,USD,139200,AU,Presencial,AU,M√©dia
4,2025,J√∫nior,Integral,Data Engineer,90000,USD,90000,US,Presencial,US,M√©dia